### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Elektroarzt** [mansellrace/comelit-esphome#1]
Hi mansellrace ... I'm trying to port your YAML code to ESP32. I did the following:
- changed ESP8266 platform to ESP32
- changed ESP8266 pins to the corresponding on ESP32 I used
- stored comelit.h in /homeassistant/esphome/

Validation is without errors. On attempt to upload I get errors you can see in the attached log file.
Do you have any idea to fix this?

[logs_esphome-web-381c28_run.txt](https://github.com/mansellrace/comelit-esphome/files/14099411/logs_esphome-web-381c28_run.txt)
[esphome-web-381c28.yaml.txt](https://github.com/mansellrace/comelit-esphome/files/14099426/esphome-web-381c28.yaml.txt)

**Comment by mansellrace** [comment]
Hi, 
The project has progressed from the version currently available on github. Both as hardware and software.

As hardware I created a new hardware version with a completely new power section, adding protections regarding undervoltages and instabilities that could occur. 

As software I have in development an external component for esphome that will be more powerful, more customizable, easier to set up. is in good progress, the receiving part works well and I am refining some small details, I need to develop the transmission part , but I think it will take a short time.

I think in a week there will be big changes on this project, stay tuned!

**Comment by Elektroarzt** [comment]
Super cool ... sounds good!

**Comment by mansellrace** [comment]
Hi! New software and schematics is online! You can test it and if you have other problems you can open another issue or contact me on mansellrace@gmail.com
